import React from 'react';
import { motion } from 'motion/react';
import { FiGithub, FiLinkedin, FiMail, FiInfo } from 'react-icons/fi';

const PageWrapper = ({ title, children }) => (
  <section className="relative z-10 max-w-4xl mx-auto px-6 pt-32 pb-24 min-h-[70vh]">
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="p-8 md:p-12 rounded-3xl bg-white/[0.02] border border-white/10 shadow-2xl"
    >
      <div className="flex items-center gap-3 mb-8 pb-6 border-b border-white/10">
        <FiInfo className="w-6 h-6 text-indigo-400" />
        <h1 className="text-3xl font-bold text-white tracking-tight">{title}</h1>
      </div>
      
      <div className="p-4 bg-indigo-500/10 border border-indigo-500/20 rounded-xl mb-8 flex items-start gap-3">
        <span className="text-indigo-400 font-bold uppercase tracking-wider text-[10px] mt-1 shrink-0 bg-indigo-500/20 px-2 py-1 rounded">Demo Notice</span>
        <p className="text-indigo-200/80 text-sm leading-relaxed">
          FinScope is a <strong>portfolio project</strong> created strictly for demonstration purposes. It is not an actual commercial financial service platform.
        </p>
      </div>

      <div className="space-y-6 text-white/70 leading-relaxed text-sm md:text-base">
        {children}
      </div>
    </motion.div>
  </section>
);

export const PrivacyPolicy = () => (
  <PageWrapper title="Privacy Policy">
    <p>
      Because FinScope is a demonstration application, we do not actively collect, store, or process real user data for any commercial purposes.
    </p>
    <h3 className="text-lg font-bold text-white mt-8 mb-4">1. Data Storage</h3>
    <p>
      Any data entered into the application (such as transactions, budgets, or custom categories) may be stored locally in your browser or on a sandbox database purely to demonstrate functionality. Do not enter real, sensitive financial information.
    </p>
    <h3 className="text-lg font-bold text-white mt-8 mb-4">2. Third-Party Sharing</h3>
    <p>
      We do not share, sell, or rent any information to third parties. There are no tracking scripts, ad networks, or analytics tools configured to harvest your personal data.
    </p>
    <h3 className="text-lg font-bold text-white mt-8 mb-4">3. Security</h3>
    <p>
      While standard authentication protocols are implemented to demonstrate technical capabilities, this is a portfolio environment. We cannot guarantee bank-level security.
    </p>
  </PageWrapper>
);

export const TermsOfService = () => (
  <PageWrapper title="Terms of Service">
    <p>
      By accessing or using FinScope, you acknowledge that this is a <strong>portfolio project</strong> built to showcase software engineering skills, not a real financial product.
    </p>
    <h3 className="text-lg font-bold text-white mt-8 mb-4">1. Use of the Application</h3>
    <p>
      You are welcome to interact with the application, create mock accounts, and test the features (like adding transactions and viewing analytics). However, you agree not to use the platform for actual financial management.
    </p>
    <h3 className="text-lg font-bold text-white mt-8 mb-4">2. No Financial Advice</h3>
    <p>
      Any insights, advice, or calculations generated by the application (including AI Wealth Advisor mockups) are simulated and do not constitute real financial, legal, or tax advice. 
    </p>
    <h3 className="text-lg font-bold text-white mt-8 mb-4">3. Limitation of Liability</h3>
    <p>
      The developer assumes no liability for any data loss, errors, or issues resulting from the use of this demonstration software. The service is provided "as is" without warranties of any kind.
    </p>
  </PageWrapper>
);

export const Contact = () => (
  <PageWrapper title="Contact the Developer">
    <p>
      Thank you for checking out FinScope! If you're interested in discussing this project, reviewing my other work, or connecting professionally, please reach out through the channels below.
    </p>
    
    <div className="grid md:grid-cols-2 gap-4 mt-8">
      <a href="https://github.com/roshanG077" target="_blank" rel="noreferrer" className="flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors group">
        <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center group-hover:scale-110 transition-transform">
          <FiGithub className="w-5 h-5 text-white" />
        </div>
        <div>
          <h4 className="font-bold text-white">GitHub</h4>
          <p className="text-xs text-white/50">View source code & projects</p>
        </div>
      </a>

      <a href="https://linkedin.com" target="_blank" rel="noreferrer" className="flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors group">
        <div className="w-10 h-10 rounded-full bg-[#0a66c2]/20 flex items-center justify-center group-hover:scale-110 transition-transform">
          <FiLinkedin className="w-5 h-5 text-[#0a66c2]" />
        </div>
        <div>
          <h4 className="font-bold text-white">LinkedIn</h4>
          <p className="text-xs text-white/50">Connect professionally</p>
        </div>
      </a>

      <a href="mailto:officialroshan077@gmail.com" className="flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors group md:col-span-2">
        <div className="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
          <FiMail className="w-5 h-5 text-emerald-400" />
        </div>
        <div>
          <h4 className="font-bold text-white">Email</h4>
          <p className="text-xs text-white/50">officialroshan077@gmail.com</p>
        </div>
      </a>
    </div>
  </PageWrapper>
);
